### ISSUE TITLE
Won´t work with LB2

### ISSUE THREAD

**Issue by jenell95** [TheAlphaRhythm/LBReceiptPrinter#3]
OS: Win 10 21H2
LioranBoard v 2.0.6.3

![image](https://user-images.githubusercontent.com/61617135/152993367-805f14f0-4756-47e2-ba6a-0c2e85957b31.png)

**Comment by BrianThePrimate** [comment]
I am having the exact same issue. Not sure what I am doing wrong here.

**Comment by jenell95** [comment]
LB2 is a totally different application. 

I personally switched over to Streamer.Bot and don’t care about LB anymore

**Comment by BrianThePrimate** [comment]
Ok, I found a work around that was brought up on the Discord channel. The new version of the printer software is at https://ko-fi.com/s/ee13c3127c That replaces the old zip file. After installing that it worked fine and I was able to get my printer printing responding to TLS tests. :)
